### ISSUE TITLE
Invalid username error message 

### ISSUE THREAD

**Issue by adoniskrasniqi** [konicm8ker/devrant-widget#2]
Kudos for the project.

Invalid username error is not clear, please specify what went wrong instead of standard error.
> “devrant-widget/includes/get-data.php”

**Comment by konicm8ker** [comment]
Thanks! I'll update that.

**Comment by konicm8ker** [comment]
Okay it's been updated. Let me know if that is better :)

**Comment by adoniskrasniqi** [comment]
It is great.
